[project]
name = "rick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.7.0",
    "httpx>=0.28.1",
    "logfire[google-genai]>=4.34.0",
    "pydantic-ai>=1.104.0",
    "python-dotenv>=1.2.2",
    "supabase>=2.31.0",
]

[dependency-groups]
dev = [
    "ty>=0.0.44",
]

[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
